[tool.poetry]
name = "interp-toxicity"
version = "0.1.0"
description = ""
authors = ["wid0gast <mohammadshaz529@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
torch = ">=2.2"
transformer-lens = "^2.15.0"
numpy=[
    {version=">=1.20,<1.25", python=">=3.8,<3.9"},
    {version=">=1.24", python=">=3.9,<3.12"},
    {version=">=1.26", python=">=3.12,<3.13"},
]
accelerate=">=0.23.0" # Needed for Llama Models
beartype="^0.14.1"
better-abc="^0.0.3"
datasets=">=2.7.1"
einops=">=0.6.0"
fancy-einsum=">=0.0.3"
jaxtyping=">=0.2.11"
pandas=">=1.1.5"
python=">=3.6,<4.0"
rich=">=12.6.0"
sentencepiece="*"
tqdm=">=4.64.1"
transformers=">=4.43"
typing-extensions="*"
wandb=">=0.13.5"
typeguard = "^4.2"
transformers-stream-generator = "^0.0.5"
plotly-utils = "^0.0.3"
eindex-callum = "^0.1.2"
hf-xet = "^1.0.3"
nltk = "^3.9.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
